name: Version Management

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "Version type"
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install bump2version
        run: pip install bump2version

      - name: Create Version Bump Branch
        run: |
          git checkout -b version-bump-${{ github.run_id }}

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version and Create Git Tag
        run: bump2version ${{ github.event.inputs.versionType }} --config-file .bumpversion.cfg

      - name: Commit Changes
        run: |
          git commit -am "Bump version via GitHub Actions"

      - name: Push Changes
        run: |
          git push --set-upstream origin version-bump-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update version
          title: "Release ${{ steps.bump-version.outputs.new_version }} [${{ github.event.inputs.versionType }}]"
          body: |
            This PR is auto-generated by the CI to bump the version.
            Changes included:
            ```
            ${{ steps.bump-version.outputs.changes }}
            ```
          branch: version-bump-${{ github.run_id }}
          base: main
